language: python
python:
  - "3.6"
jobs:
  include:
    - stage: build
      script: ./ops/bin/build
    - stage: test
      script: ./ops/bin/tester
    - stage: deploy
      script: ./ops/bin/deploy