language: python
python:
  - "3.6"
jobs:
  include:
    - stage: build
      script: echo "haha oops forgot to do this"
    - stage: test
      script: echo "I know what to do"
    - stage: deploy
      script: echo "deploy this"