language: python
python:
  - "3.6"
jobs:
  include:
    - stage: build
      script: ./deploy/bin/build
    - stage: test
      script: ./deploy/bin/test
    - stage: deploy
      script: ./deploy/bin/deploy